sudo: false
language: scala
addons:
  apt:
    packages:
      - nodejs
install: true # disable travis' default mvn install before running the tests
scala:
  - "2.11.8"
jdk:
  - oraclejdk8
script: mvn clean test package
cache:
  directories:
    - $HOME/.m2/repository
