scheduleHorizonSeconds: 60
master: local
# When the server name is specified via '--', an internal ZK Server is started on this port.
# Do not use this setting in production, it does not persist the data in any reliable way.
zookeeperServers: --:28281

http:

    adminPort: 4401
    port: 4400
    rootPath: "/scheduler/*"

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
