scheduleHorizonSeconds: 60
master: local

http:

    adminPort: 4401
    port: 4400
    rootPath: "/scheduler/*"

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
